name: Deploy

on:
  # Depends on the Docker Publish workflow to be completed
  workflow_run:
    workflows: ["Docker Publish"]
    branches:
      - main
    types:
      - completed

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v2

      - name: Create required directories
        run: mkdir -p .appcd/charts && chmod 777 .appcd -R

      - name: Login to docker
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: run appCD
        run: |
          docker run --rm \
          --workdir=/code  \
          -v $PWD:/code ghcr.io/appcd-dev/appcd-dist/appcd:main \
          generate --mode ci --output=/code/.appcd/charts
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: "2"

      - name: Configure Kubernetes access
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-2
          aws eks update-kubeconfig --name demo-demo

      - name: Install Helm Diff
        run: |
          helm plugin install https://github.com/databus23/helm-diff

      - name: Helm diff
        run: |
          helm diff upgrade demo-chart ./.appcd/charts/dogeapi -f .appcd/overrides/dogeapi/values.yaml --install

      - name: Helm Upgrade
        run: |
          helm upgrade demo-chart ./.appcd/charts/dogeapi -f .appcd/overrides/dogeapi/values.yaml --install --wait
